---

- name: Provisioning fansible-tywin
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  roles:
    - ubuntu-apt
    - create-www-data-user
    - nodejs
    - composer
    - ubuntu-nodejs-nginx


